### ISSUE TITLE
Fatal error  Uncaught ArgumentCountError for Create Form

### ISSUE THREAD

**Issue by Rayiumir** [codemonkey-jack/kb-support#253]
Hi...

We translated your plugin and so far there was no problem.
But the problem is that when we create a new form and use the short code in the pages, we encounter an error and it is the result of interference with the class-wp-editor.php file in the WordPress core itself.

The following error:

`Fatal error: Uncaught ArgumentCountError: 44 arguments are required, 2 given in www\wordpress\wp-includes\class-wp-editor.php:305`

**Comment by razvanaldea89** [comment]
Hello @RaymondTomcat ,

Could you let me know what version of WordPress you are using?

**Comment by RaymondTomcat** [comment]
@razvanaldea89
Latest version 6.1.1

**Comment by razvanaldea89** [comment]
Thank you for the info. Could you please check using a shortcode from another plugin ( Modula for example ) and see if it gives the same error? Also, could you please let me know what theme are you using?

Warmly,
Razvan

**Comment by RaymondTomcat** [comment]
@razvanaldea89 
I tested the modula plugin and there was no problem and I did not see any errors.
The WordPress theme is specially designed and coded, and the default themes of WordPress are not used.

**Comment by razvanaldea89** [comment]
Thanks for the info.

Could you please install this plugin: https://wordpress.org/plugins/health-check/ ?
After you install and activate the above plugin it has a Troubleshooting mode which allows you to have a vanilla WordPress session, where all plugins are disabled, and a default theme is used, but only for your user – your visitors will still see the normal website.
Go to its troubleshoot mode and only activate this plugin and see if the same happens with the theme and no other plugins.
Please let me know how it goes and what you find!


Warmly,
Razvan

**Comment by razvanaldea89** [comment]
Just to be clear, you've tested the shortcode with no plungins active ( except kb support ) and a default WordPress theme, and still same error. Is that correct?

**Comment by RaymondTomcat** [comment]
@razvanaldea89 
Yes
I disabled all plugins except kb support, and the same error problem persists.

**Comment by TeoAlex** [comment]
Hi @RaymondTomcat ,

Can you please give us more details so we can replicate the issue on our end?

1. If you change your site's or user language to default English (United States) the error still shows?
2. How did you translate the plugin? can we have those translation files aswell?

**Comment by RaymondTomcat** [comment]
Hi @TeoAlex 

1. Yes, even if WordPress is in English, it gives an error
2. I translated with Loco Translate plugin and of course I used poedit software.
3. file fa.po https://ufile.io/hue14z05

**Comment by TeoAlex** [comment]
I installed the submitted language files and even so, i could not reproduce the issue,
Can you please create a new submission form, save it without adding any more custom fields to it and try adding that one's shortcode to a new page?

**Comment by RaymondTomcat** [comment]
@TeoAlex
Yes ...
I will try again in the main host and let you know.

**Comment by RaymondTomcat** [comment]
Hi @TeoAlex
I installed the plugin again and added the translated file.
We have two textareas in the submission form section.

1. Textarea simple
2. Rich Text Editor

The first one works.
The second one does not work and its textarea is blocked and does not show an error, while it used to show.

1. https://s26.picofile.com/file/8459751868/1_KB.png
2. https://s26.picofile.com/file/8459751876/2_KB.png
